### PR TITLE
10 settings docs

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/platformsh/platformsh-example-backdrop/issues/10

### CODE REVIEW

**Comment by Crell** [comment]
@jenlampton, do you have merge access on this repo?  I'm not sure who does, but if so feel free to merge when you're happy.  No need to wait for us. :smile:

**Comment by serundeputy** [comment]
@Crell I don't know about @jenlampton but my access to the p.sh repo was revoked on 

> Tue, Jan 29, 5:13 PM (13 days ago)

**Comment by jenlampton** [comment]
> @jenlampton, do you have merge access on this repo?

No I don't. Is there an official process to request access?

**Comment by Crell** [comment]
Ah, probably because we enabled 2FA as a requirement for all accounts at the end of January.  Enable 2FA on your GitHub account and let me know that you've done so and I can add both of you.

**Comment by jenlampton** [comment]
2fa is already on for my account.

**Comment by serundeputy** [comment]
2fa is on for me as well.

**Comment by Crell** [comment]
I've sent invites to you both.

**Comment by jenlampton** [comment]
Thanks @Crell I now have access. Merging away :)

**Pull request merged**
